### ISSUE TITLE
online documentation is still available ?

### ISSUE THREAD

**Issue by jimingda** [robotology/grasp#6]
Hi,

does the web still available? Or where can i find related document
[https://robotology.github.com/grasp](https://robotology.github.com/grasp)

Thanks.

**Comment by pattacini** [comment]
Hi @jimingda 

The documentation is available at http://robotology.github.io/grasp/.
I've fixed the main README via https://github.com/robotology/grasp/commit/9069cf40ebfe26ba17274fbd16b3784acb614d61.

That being said, this project is no longer maintained.

**Comment by pattacini** [comment]
To expand on this, you can find here in the repo the code for these two papers:
- https://ieeexplore.ieee.org/document/6766495
- https://ieeexplore.ieee.org/document/6907648

However, as said above, this code is no longer maintained.
